name: oraah_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <3.4.5 '


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.1
  get_it: ^7.6.4
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.3.4
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  flutter_swiper_view: ^1.1.8
  flutter_staggered_animations: ^1.1.1
  network_info_plus: ^4.1.0+1
  flutter_launcher_icons: ^0.13.1
  animated_snack_bar: ^0.4.0
  elegant_notification: ^1.13.0
  share_plus: ^7.2.2
  

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#322653"
  color_dark: "#322653"
  image: "assets/oraahyo_icon.png"
  fullscreen: true
  android_12:
    image: "assets/oraahyo_icon.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/app_icons/android_icon.png"
  min_sdk_android: 21 
  remove_alpha_ios: true



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  line_awesome_flutter: ^2.0.0
  google_fonts: ^5.1.0
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  auto_size_text: ^3.0.0
  path_provider: ^2.1.0
  clipboard: ^0.1.3

  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.3
  lottie: ^2.6.0
  flutter_lints: ^2.0.0
  image_picker: ^1.0.7
  flutter_colorpicker: ^1.0.3
  
  



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts: 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
    - family: BreeSerif 
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-italic.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Prozalibre
      fonts:
        - asset: assets/fonts/Prozalibre-Regular.ttf
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces-Italic-VariableFont_SOFT,WONK,opsz,wght.ttf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf





